---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/login":
    post:
      summary: Login de usuário
      tags:
      - Autenticação
      parameters: []
      responses:
        '200':
          description: Login realizado com sucesso
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: usuario@example.com
                password:
                  type: string
                  example: senha123
              required:
              - email
              - password
  "/api/v1/authors":
    get:
      summary: Lista autores
      tags:
      - Autores
      responses:
        '200':
          description: Autores listados
    post:
      summary: Cria autor
      tags:
      - Autores
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Autor criado
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                  - Person
                  - Institution
                name:
                  type: string
                birth_date:
                  type: string
                  format: date
                city:
                  type: string
              required:
              - type
              - name
  "/api/v1/materials":
    get:
      summary: Lista materiais
      tags:
      - Materiais
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: q
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Materiais listados
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
