---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/materials":
    get:
      summary: Lista materiais
      tags:
      - Materiais
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: q
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Materiais listados
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
